# This is a basic workflow to help you get started with Actions

name: Build SchwachMatt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup premake
      - name: Setup Premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta1"
      
      # Premake
      - name: Premake gmake2
        run: premake5 gmake2
      
      # Create the external/ folder
      - name: Makedir external
        run: mkdir external
        
      - name: Cache Boost_1.77
        id: boost-cache
        uses: actions/cache@v2
        with:
          path: external/boost_1_77_0
          key: external-boost-1_77
          
      - name: Get Boost
        if: steps.boost-cache.outputs.cache-hit != 'true'
        run: wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.zip -P external
      
      - name: Get unzip
        if: steps.boost-cache.outputs.cache-hit != 'true'
        run: sudo apt-get install zip unzip
        
      - name: Extract Boost
        if: steps.boost-cache.outputs.cache-hit != 'true'
        run: unzip external/boost_1_77_0.zip -d external

      # Runs a set of commands using the runners shell
      - name: Run build
        run: make SchwachMatt
